### ISSUE TITLE
resolver does not work correctly.

### ISSUE THREAD

**Issue by aplsms** [drone-plugins/drone-git#67]
Hello,

resolver on git plugin is not working correctly.

Error message:
```
+ git init
Initialized empty Git repository in /drone/src/git.domain.com/apl/test/.git/
+ git remote add origin https://git.domain.com/apl/test.git
+ git fetch --no-tags --depth=50 origin +refs/heads/master:
fatal: unable to access 'https://git.domain.com/apl/test.git/': Could not resolve host: git.domain.com
exit status 128
```
worker's logs:
```
{"time":"2018-04-03T06:45:16Z","level":"debug","message":"request next execution"}
go package net: GODEBUG setting forcing use of Go's resolver
go package net: hostLookupOrder(drone.domain.com) = files,dns
{"time":"2018-04-03T06:45:29Z","level":"debug","repo":"apl/test","build":"73","id":"196","message":"received execution"}
{"time":"2018-04-03T06:45:29Z","level":"debug","repo":"apl/test","build":"73","id":"196","message":"listen for cancel signal"}
{"time":"2018-04-03T06:45:29Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","exit_code":0,"exited":false,"message":"update step status"}
{"time":"2018-04-03T06:45:29Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","exit_code":0,"exited":false,"message":"update step status complete"}
{"time":"2018-04-03T06:45:30Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","message":"log stream opened"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","message":"log stream copied"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","message":"log stream uploading"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","message":"log stream upload complete"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","message":"log stream closed"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","exit_code":1,"exited":true,"message":"update step status"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","image":"plugins/git:latest","stage":"git","exit_code":1,"exited":true,"message":"update step status complete"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","error":"","exit_code":1,"message":"pipeline complete"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","message":"uploading logs"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","message":"uploading logs complete"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","error":"","exit_code":1,"message":"updating pipeline status"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","message":"stop listening for cancel signal"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","message":"updating pipeline status complete"}
{"time":"2018-04-03T06:45:35Z","level":"debug","message":"request next execution"}
{"time":"2018-04-03T06:45:35Z","level":"debug","repo":"apl/test","build":"73","id":"196","message":"pipeline done"}
```
I can resolve any hosts from container

```
apl@beta:~/GIT/test$ docker exec -it drone-worker cat /etc/resolv.conf
search domain.com apl
nameserver 127.0.0.11
options ndots:0

apl@beta:~/GIT/test$ docker exec -it drone-worker nslookup git.domain.com 127.0.0.11
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      git.domain.com
Address 1: 192.168.1.7 git.domain.com

apl@beta:~/GIT/test$ docker exec -it drone-worker cat /etc/hosts
127.0.0.1       localhost
192.168.1.2     drone.domain.com
192.168.1.7     git.domain.com
172.19.1.15     5c72078eaeb0
```
I can clone repository using regular git inside worker container.

```
/ # git clone https://git.domain.com/apl/test.git
Cloning into 'test'...
remote: Counting objects: 86, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 86 (delta 17), reused 7 (delta 1)
Unpacking objects: 100% (86/86), done.
```

docker-compose.yml:

```yaml
version: '3'

services:
  drone-server:
    image:  ap-drone-server:latest
    container_name: drone-server
    ports:
      - 8088:8000
      - 9000:9000
    volumes:
      - /Data/Drone/:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=https://drone.domain.com
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=https://git.domain.com
      - DRONE_SECRET=2485a42e37b91fb033b328c333b1f6a9
      - GODEBUG=netdns=go
    dns:
      - 192.168.1.2
      - 192.168.1.4
    dns_search:
      - domain.com
      - apl

  drone-agent:
    image: ap-drone-agent
    container_name: drone-worker
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone.domain.com:9000
      - DRONE_SECRET=2485a42e37b91fb033b328c333b1f6a9
      - GODEBUG=netdns=9+go
      - DEBUG=true
    dns:
      - 192.168.1.2
      - 192.168.1.4
    dns_search:
      - domain.com
      - apl
    extra_hosts:
      - "git.domain.com:192.168.1.2"
      - "drone.domain.com:192.168.1.2"

networks:
  default:
    external:
      name: br-pub
```

drone-agent version 0.8.5
drone-server version 0.8.5
Docker version 18.03.0-ce, build 0520e24
