### ISSUE TITLE
plugins git clone public is unsuccessful in ARM64

### ISSUE THREAD

**Issue by DragonSuper** [drone-plugins/drone-git#85]
Hi, I can not commit the issue in https://discourse.drone.io/

drone: 1.0
This command is ok.

```
docker run --rm \
    -e DRONE_REMOTE_URL=http://IP:33000/xiaozheng8187/godev.git \
    -e DRONE_WORKSPACE=/go/src/github.com/xiaozheng8187/godev \
    -e DRONE_BUILD_EVENT=push \
    -e DRONE_COMMIT_SHA=a14c724b8d00eff659d9351ec560b67519dbf226 \
    -e DRONE_COMMIT_REF=refs/heads/master \
    plugins/git:linux-arm64
```
But this command is not ok, git clone hang up 
CI/CD is gogs 0.11

```
kind: pipeline
name: godev
clone:
  disable: true
platform:
  os: linux
  arch: arm64
workspace:
  base: /go
  path: src/gogs.xiaozheng.com/super/godev
steps:
- name: clone
  image: plugins/git:linux-arm64
  commands:
  - git clone http://IP:33000/xiaozheng8187/godev.git
```

docker logs j521jqk7ugfots7utxy05mp2u10s88mx

this log as:
```
+ git clone http://IP:33000/xiaozheng8187/godev.git
Cloning into 'godev'...
```
