### ISSUE TITLE
fatal: could not read Username for 'https://git.mydomain.com': No such device or address

### ISSUE THREAD

**Issue by GCorbel** [drone-plugins/drone-git#88]
I recently installed a server with Drone 1.x and I have a repo with submodules. I have this .drone.yml file : 

```
---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 1
    recursive: true
    submodule_override:
      vendor/plugins/acts_as_list: https://git.mydomain.com/ccp-v2/acts_as_list.git
// ...
```

When I run a build, it gives the error `fatal: could not read Username for 'https://git.mydomain.com': No such device or address`.

I did some tests and I was able to determine than git and ssh configs aren't shared between the host and the container. I saw #87 will partially fix the problem because we'll be able to specify the username but it still require the password. There's maybe a way to add the password in variable but this not ideal.

It seems that sharing the `id_rsa` key is enough to make the `git clone` working. I didn't found a way to do this.

It was working with drone 0.8.x.

Is there something I missed?
